version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: AstaYc
      POSTGRES_PASSWORD: urPassword
      POSTGRES_DB: hotel_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
